Add author and repository entries to document
alejandrosame/code2vec pull request #2
Opened 2018-08-24 22:09 UTC by alejandrosame

The changes proposed provide with separate repository and author entries for each function UAST document.

This information can be used to experiment with different train/test partitions based on repository or author.

Signed-off-by: Alejandro Sanchez Medina <alejandrosanchzmedina@gmail.com>

2018-08-25 05:04 UTC, xennygrimmato requested changes

2018-08-25 05:04 UTC, xennygrimmato commented on src/transformers/deanonymizer.py
> +class Deanonymizer(Transformer):
Can you add a comment here to describe what the intended functionality of the class is?

2018-08-25 05:04 UTC, xennygrimmato commented on src/cmd/code2vec_extract_features.py
> +        .link(UastRow2ExtendedDocument()) \
Can you add some reference to `UastRow2ExtendedDocument`? I want to understand the difference between `UastRow2Document` and `UastRow2ExtendedDocument `.

2018-08-26 15:00 UTC, alejandrosame commented on src/transformers/deanonymizer.py
> +class Deanonymizer(Transformer):
Let me know if the message is not clear enough :)

2018-08-26 15:02 UTC, alejandrosame commented on src/cmd/code2vec_extract_features.py
> +        .link(UastRow2ExtendedDocument()) \
I added comments to the UastRow2ExtendedDocument class that should clarify this difference. Let me know if it's not clear enough.

After you check this I will make another amend to move the file "extended_document_features.py" file from extractors folder to transformers, as it should be there.

2020-08-18 18:13 UTC, merged